title: A German Works Council
description: Information about establishing a works council for employees in Germany
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

header_pages:
  - works-meeting.md
  - faq.md
